/**
 * Do not edit this file.
 * This file is automatic generated to get type help.
 */

import { combineStores } from "dob"

import { ApplicationAction, ApplicationStore } from "../stores/application"

const stores = combineStores({ ApplicationAction, ApplicationStore })

export { stores }
