/**
 * Do not edit this file.
 * This file is automatic generated to get type help.
 */

import { combineStores } from "dob"
import { ApplicationAction, ApplicationStore } from "../stores/application"
import { UserAction, UserStore } from "../stores/user"

const stores = combineStores({
  ApplicationAction,
  ApplicationStore,
  UserAction,
  UserStore
})

export { stores }
