"use strict";
/**
 * Do not edit this file.
 * This file is automatic generated to get type help.
 */
Object.defineProperty(exports, "__esModule", { value: true });
const dob_1 = require("dob");
const application_1 = require("../stores/application");
const stores = dob_1.combineStores({ ApplicationAction: application_1.ApplicationAction, ApplicationStore: application_1.ApplicationStore });
exports.stores = stores;
//# sourceMappingURL=helper.js.map